repos:
  - repo: local
    hooks:
      - id: pytest-tests
        name: Run Unit Tests
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
